[build-system]
requires = [
    "setuptools>=61"
]
build-backend = "setuptools.build_meta"

[project]
name = "loganmatic"
version = "0.0.16"
authors = [
  { name="Gabriel Logan" },
]
description = "Loganmatic package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/gabriel-logan/Math_Lib/tree/main/packages/python"
"Bug Tracker" = "https://github.com/gabriel-logan/Math_Lib/tree/main/packages/python"
